title: Kamila Młynarczyk
subtitle: Fullstack Developer, inżynier informatyki
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio
author: Kamila Młynarczyk
email: kamilaxmlynarczyk@gmail.com
avatar: assets/images/avatar.jpg

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://linkedin.com/in/kamila-młynarczyk-2a2b97350
github_url: https://https://github.com/KamilaMlyn
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

collections: [sections-home, sections-skills]